baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-bearblog"
title = "ht.xyz"

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Writings"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1
[[menu.main]]
name = "Mahabharat"
url = "/mahabharat/"
weight = 2
[[menu.main]]
name = "Subscribe"
url = "/index.xml"
weight = 2

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Copyleft 2021 | [Github](https://github.com/gtlsgamr/htxyz)"
