name = "hugo-htxyz"
license = "GPLv3"
licenselink = "https://github.com/gtlsgamr/hugo-htxyz/blob/master/LICENSE"
description = "Custom hugo theme for my blog"
homepage = "https://github.com/gtlsgamr/hugo-htxyz/"
demosite = "hitarththummar.xyz"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "gtlsgamr"
  homepage = "https://github.com/gtlsgamr"
